language: java
jdk:
  - oraclejdk7

install: true
script:
  -  "cd modules;mvn clean test"
  - jdk_switcher use openjdk6
  - "mvn test"
  - jdk_switcher use oraclejdk8
  - "mvn test" 
branches:
  only:
    - master 
